#!/bin/bash

rsync -a $HOME/.tmux.conf tmux/.tmux.conf
rsync -a $HOME/.tmux-gitbar.conf tmux/.tmux-gitbar.conf
rsync -a $HOME/.tmux/plugins tmux/.tmux/

rsync -a $HOME/.gitconfig  git/.gitconfig
rsync -a $HOME/.gitignore  git/.gitignore

rsync -a $HOME/.vim/after  vim/.vim/
rsync -a $HOME/.vim/mysnips  vim/.vim/
rsync -a $HOME/.vim/skel.f90  vim/.vim/

echo "Do not forget to manually check .vimrc!"

